name: Continuous Integration

on:
    push

jobs:
    build_and_pull:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Login
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN}}



