on: push

jobs:
  demo1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Olá, mundo"
      - name: setp2
        run: |
            echo "Mensagem 2"
            echo "Mensagem 2"
            ls -la
